spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 3000 #连接超时时间
    jedis:
      pool:
        max-active: 100 #连接池中的最大连接数，负值表示没有限制，默认为8
        max-wait: 3000 #连接池最大阻塞等待时间，负值表示没有限制
        max-idle: 20 #连接池中最大的空闲连接数
        min-idle: 0 #连接池中最小的空闲连接数

  thymeleaf:
    cache: false
    mode: LEGACYHTML5
logging:
  file:
    path: E:\University\Study\Java\SpringBoot\log


